=== nawojmonika/PKCK/src/plytoteka.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/plytoteka.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE __ROOT__ SYSTEM "plytoteka.dtd">

    <__ROOT__>
    ...
    </__ROOT__>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT __ROOT__ (naglowek|plyty)*>
<!ATTLIST __ROOT__
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT naglowek (autorzy|data-oddania)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT autorzy (autor)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT autor (imie|nazwisko|index)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT imie (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nazwisko (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT index (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT data-oddania (dzień|DD|MM|YYYY)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dzień (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DD (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MM (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT YYYY (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plyty (plyta)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plyta (tytul|wykonawca|gatunek|cena)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tytul (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT wykonawca (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT gatunek (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cena (#PCDATA)>

=== nawojmonika/PKCK/src/plytoteka.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="plytoteka.css"?>

<!DOCTYPE __ROOT__ SYSTEM 'plytoteka.dtd'>

<__ROOT__ version="1">
    <naglowek>
        <autorzy>
            <autor>
                <imie>
                    Artur
                </imie>
                <nazwisko>
                    Dziedziczak
                </nazwisko>
                <index>
                    211802
                </index>
            </autor>
            <autor>
                <imie>
                    Monika
                </imie>
                <nazwisko>
                    Nawój
                </nazwisko>
                <index>
                    211828
                </index>
            </autor>
        </autorzy>
        <data-oddania>
            <dzień>Sobota</dzień>
            <DD>06</DD>
            <MM>03</MM>
            <YYYY>2019</YYYY>
        </data-oddania>
    </naglowek>
</__ROOT__>
